runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: numpy
  version: latest

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  secure: always
# [END handlers]
